### ISSUE TITLE
500 on privacy page

### ISSUE THREAD

**Issue by breunigs** [breunigs/hipsterpizza#28]
```
ActionView::Template::Error (no implicit conversion of Hash into String):
  vendor/bundle/ruby/2.1.0/gems/temple-0.6.8/lib/temple/filters/static_merger.rb:22:in `block in on_multi'
  vendor/bundle/ruby/2.1.0/gems/temple-0.6.8/lib/temple/filters/static_merger.rb:19:in `each'
  vendor/bundle/ruby/2.1.0/gems/temple-0.6.8/lib/temple/filters/static_merger.rb:19:in `on_multi'
  (eval):5:in `dispatcher'
  vendor/bundle/ruby/2.1.0/gems/temple-0.6.8/lib/temple/mixins/dispatcher.rb:49:in `compile'
  vendor/bundle/ruby/2.1.0/gems/temple-0.6.8/lib/temple/mixins/dispatcher.rb:45:in `call'
  vendor/bundle/ruby/2.1.0/gems/temple-0.6.8/lib/temple/engine.rb:50:in `block in call'
  vendor/bundle/ruby/2.1.0/gems/temple-0.6.8/lib/temple/engine.rb:50:in `each'
  vendor/bundle/ruby/2.1.0/gems/temple-0.6.8/lib/temple/engine.rb:50:in `inject'
  vendor/bundle/ruby/2.1.0/gems/temple-0.6.8/lib/temple/engine.rb:50:in `call'
  vendor/bundle/ruby/2.1.0/gems/temple-0.6.8/lib/temple/mixins/template.rb:10:in `compile'
  vendor/bundle/ruby/2.1.0/gems/temple-0.6.8/lib/temple/templates/rails.rb:34:in `call'
  vendor/bundle/ruby/2.1.0/gems/actionview-4.1.4/lib/action_view/template.rb:270:in `compile'
  vendor/bundle/ruby/2.1.0/gems/actionview-4.1.4/lib/action_view/template.rb:245:in `block (2 levels) in compile!'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.4/lib/active_support/notifications.rb:161:in `instrument'
  vendor/bundle/ruby/2.1.0/gems/actionview-4.1.4/lib/action_view/template.rb:339:in `instrument'
  vendor/bundle/ruby/2.1.0/gems/actionview-4.1.4/lib/action_view/template.rb:244:in `block in compile!'
  vendor/bundle/ruby/2.1.0/gems/actionview-4.1.4/lib/action_view/template.rb:232:in `synchronize'
  vendor/bundle/ruby/2.1.0/gems/actionview-4.1.4/lib/action_view/template.rb:232:in `compile!'
  vendor/bundle/ruby/2.1.0/gems/actionview-4.1.4/lib/action_view/template.rb:144:in `block in render'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.4/lib/active_support/notifications.rb:161:in `instrument'
  vendor/bundle/ruby/2.1.0/gems/actionview-4.1.4/lib/action_view/template.rb:339:in `instrument'
  vendor/bundle/ruby/2.1.0/gems/actionview-4.1.4/lib/action_view/template.rb:143:in `render'
  vendor/bundle/ruby/2.1.0/gems/actionview-4.1.4/lib/action_view/renderer/template_renderer.rb:55:in `block (2 levels) in render_template'
  vendor/bundle/ruby/2.1.0/gems/actionview-4.1.4/lib/action_view/renderer/abstract_renderer.rb:38:in `block in instrument'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.4/lib/active_support/notifications.rb:159:in `block in instrument'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.4/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.4/lib/active_support/notifications.rb:159:in `instrument'
  vendor/bundle/ruby/2.1.0/gems/actionview-4.1.4/lib/action_view/renderer/abstract_renderer.rb:38:in `instrument'
  vendor/bundle/ruby/2.1.0/gems/actionview-4.1.4/lib/action_view/renderer/template_renderer.rb:54:in `block in render_template'
  vendor/bundle/ruby/2.1.0/gems/actionview-4.1.4/lib/action_view/renderer/template_renderer.rb:62:in `render_with_layout'
  vendor/bundle/ruby/2.1.0/gems/actionview-4.1.4/lib/action_view/renderer/template_renderer.rb:53:in `render_template'
  vendor/bundle/ruby/2.1.0/gems/actionview-4.1.4/lib/action_view/renderer/template_renderer.rb:17:in `render'
  vendor/bundle/ruby/2.1.0/gems/actionview-4.1.4/lib/action_view/renderer/renderer.rb:42:in `render_template'
  vendor/bundle/ruby/2.1.0/gems/actionview-4.1.4/lib/action_view/renderer/renderer.rb:23:in `render'
  vendor/bundle/ruby/2.1.0/gems/actionview-4.1.4/lib/action_view/rendering.rb:99:in `_render_template'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.4/lib/action_controller/metal/streaming.rb:217:in `_render_template'
  vendor/bundle/ruby/2.1.0/gems/actionview-4.1.4/lib/action_view/rendering.rb:82:in `render_to_body'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.4/lib/action_controller/metal/rendering.rb:32:in `render_to_body'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.4/lib/action_controller/metal/renderers.rb:32:in `render_to_body'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.4/lib/abstract_controller/rendering.rb:25:in `render'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.4/lib/action_controller/metal/rendering.rb:16:in `render'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.4/lib/action_controller/metal/instrumentation.rb:41:in `block (2 levels) in render'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.4/lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
  /usr/lib/ruby/2.1.0/benchmark.rb:294:in `realtime'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.4/lib/active_support/core_ext/benchmark.rb:12:in `ms'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.4/lib/action_controller/metal/instrumentation.rb:41:in `block in render'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.4/lib/action_controller/metal/instrumentation.rb:84:in `cleanup_view_runtime'
  vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.4/lib/active_record/railties/controller_runtime.rb:25:in `cleanup_view_runtime'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.4/lib/action_controller/metal/instrumentation.rb:40:in `render'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.4/lib/action_controller/metal/implicit_render.rb:10:in `default_render'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.4/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.4/lib/abstract_controller/base.rb:189:in `process_action'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.4/lib/action_controller/metal/rendering.rb:10:in `process_action'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.4/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.4/lib/active_support/callbacks.rb:113:in `call'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.4/lib/active_support/callbacks.rb:113:in `call'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.4/lib/active_support/callbacks.rb:166:in `block in halting'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.4/lib/active_support/callbacks.rb:166:in `call'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.4/lib/active_support/callbacks.rb:166:in `block in halting'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.4/lib/active_support/callbacks.rb:166:in `call'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.4/lib/active_support/callbacks.rb:166:in `block in halting'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.4/lib/active_support/callbacks.rb:166:in `call'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.4/lib/active_support/callbacks.rb:166:in `block in halting'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.4/lib/active_support/callbacks.rb:229:in `call'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.4/lib/active_support/callbacks.rb:229:in `block in halting'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.4/lib/active_support/callbacks.rb:166:in `call'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.4/lib/active_support/callbacks.rb:166:in `block in halting'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.4/lib/active_support/callbacks.rb:86:in `call'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.4/lib/active_support/callbacks.rb:86:in `run_callbacks'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.4/lib/abstract_controller/callbacks.rb:19:in `process_action'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.4/lib/action_controller/metal/rescue.rb:29:in `process_action'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.4/lib/action_controller/metal/instrumentation.rb:31:in `block in process_action'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.4/lib/active_support/notifications.rb:159:in `block in instrument'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.4/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.4/lib/active_support/notifications.rb:159:in `instrument'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.4/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.4/lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
  vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.4/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.4/lib/abstract_controller/base.rb:136:in `process'
  vendor/bundle/ruby/2.1.0/gems/actionview-4.1.4/lib/action_view/rendering.rb:30:in `process'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.4/lib/action_controller/metal.rb:196:in `dispatch'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.4/lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.4/lib/action_controller/metal.rb:232:in `block in action'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.4/lib/action_dispatch/routing/route_set.rb:82:in `call'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.4/lib/action_dispatch/routing/route_set.rb:82:in `dispatch'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.4/lib/action_dispatch/routing/route_set.rb:50:in `call'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.4/lib/action_dispatch/journey/router.rb:71:in `block in call'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.4/lib/action_dispatch/journey/router.rb:59:in `each'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.4/lib/action_dispatch/journey/router.rb:59:in `call'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.4/lib/action_dispatch/routing/route_set.rb:678:in `call'
  vendor/bundle/ruby/2.1.0/gems/http_accept_language-2.0.1/lib/http_accept_language/middleware.rb:13:in `call'
  vendor/bundle/ruby/2.1.0/gems/rack-1.5.2/lib/rack/etag.rb:23:in `call'
  vendor/bundle/ruby/2.1.0/gems/rack-1.5.2/lib/rack/conditionalget.rb:25:in `call'
  vendor/bundle/ruby/2.1.0/gems/rack-1.5.2/lib/rack/head.rb:11:in `call'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.4/lib/action_dispatch/middleware/params_parser.rb:27:in `call'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.4/lib/action_dispatch/middleware/flash.rb:254:in `call'
  vendor/bundle/ruby/2.1.0/gems/rack-1.5.2/lib/rack/session/abstract/id.rb:225:in `context'
  vendor/bundle/ruby/2.1.0/gems/rack-1.5.2/lib/rack/session/abstract/id.rb:220:in `call'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.4/lib/action_dispatch/middleware/cookies.rb:560:in `call'
  vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.4/lib/active_record/query_cache.rb:36:in `call'
  vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:621:in `call'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.4/lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.4/lib/active_support/callbacks.rb:82:in `run_callbacks'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.4/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.4/lib/action_dispatch/middleware/remote_ip.rb:76:in `call'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.4/lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.4/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  vendor/bundle/ruby/2.1.0/gems/railties-4.1.4/lib/rails/rack/logger.rb:38:in `call_app'
  vendor/bundle/ruby/2.1.0/gems/railties-4.1.4/lib/rails/rack/logger.rb:20:in `block in call'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.4/lib/active_support/tagged_logging.rb:68:in `block in tagged'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.4/lib/active_support/tagged_logging.rb:26:in `tagged'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.4/lib/active_support/tagged_logging.rb:68:in `tagged'
  vendor/bundle/ruby/2.1.0/gems/railties-4.1.4/lib/rails/rack/logger.rb:20:in `call'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.4/lib/action_dispatch/middleware/request_id.rb:21:in `call'
  vendor/bundle/ruby/2.1.0/gems/rack-1.5.2/lib/rack/methodoverride.rb:21:in `call'
  vendor/bundle/ruby/2.1.0/gems/rack-1.5.2/lib/rack/runtime.rb:17:in `call'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.4/lib/action_dispatch/middleware/static.rb:64:in `call'
  vendor/bundle/ruby/2.1.0/gems/rack-1.5.2/lib/rack/sendfile.rb:112:in `call'
  vendor/bundle/ruby/2.1.0/gems/railties-4.1.4/lib/rails/engine.rb:514:in `call'
  vendor/bundle/ruby/2.1.0/gems/railties-4.1.4/lib/rails/application.rb:144:in `call'
  vendor/bundle/ruby/2.1.0/gems/rack-1.5.2/lib/rack/content_length.rb:14:in `call'
  vendor/bundle/ruby/2.1.0/gems/puma-2.9.0/lib/puma/server.rb:490:in `handle_request'
  vendor/bundle/ruby/2.1.0/gems/puma-2.9.0/lib/puma/server.rb:361:in `process_client'
  vendor/bundle/ruby/2.1.0/gems/puma-2.9.0/lib/puma/server.rb:254:in `block in run'
  vendor/bundle/ruby/2.1.0/gems/puma-2.9.0/lib/puma/thread_pool.rb:92:in `call'
  vendor/bundle/ruby/2.1.0/gems/puma-2.9.0/lib/puma/thread_pool.rb:92:in `block in spawn_thread'
```

**Comment by breunigs** [comment]
fixed somewhere in devel
